-- MySQL Script generated by MySQL Workbench
-- 04/17/17 13:33:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school-register
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school-register
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school-register` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema school-register-showroom
-- -----------------------------------------------------
USE `school-register` ;

-- -----------------------------------------------------
-- Table `school-register`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-register`.`room` (
  `idRoom` INT NOT NULL AUTO_INCREMENT,
  `Floor` INT NOT NULL,
  `LIM` TINYINT(1) NOT NULL,
  `NumeroAula` INT NOT NULL,
  PRIMARY KEY (`idRoom`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school-register`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-register`.`branch` (
  `idBranch` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `StartDate` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBranch`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school-register`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-register`.`class` (
  `Name` CHAR(8) NOT NULL,
  `fk_room` INT NULL,
  `fk_branch` INT NULL,
  INDEX `fk_classes_rooms1_idx` (`fk_room` ASC),
  INDEX `fk_classes_branch1_idx` (`fk_branch` ASC),
  PRIMARY KEY (`Name`),
  CONSTRAINT `fk_classes_rooms`
    FOREIGN KEY (`fk_room`)
    REFERENCES `school-register`.`room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_classes_branch`
    FOREIGN KEY (`fk_branch`)
    REFERENCES `school-register`.`branch` (`idBranch`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school-register`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school-register`.`student` (
  `FiscalCode` VARCHAR(16) NOT NULL,
  `Name` VARCHAR(80) NOT NULL,
  `Surname` VARCHAR(80) NOT NULL,
  `Age` INT NOT NULL,
  `Birthday` DATETIME NOT NULL,
  `Email` VARCHAR(80) NULL,
  `fk_class` CHAR(8) NOT NULL,
  PRIMARY KEY (`FiscalCode`),
  INDEX `fk_student_class1_idx` (`fk_class` ASC),
  CONSTRAINT `fk_student_class`
    FOREIGN KEY (`fk_class`)
    REFERENCES `school-register`.`class` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
